### ISSUE TITLE
'About' screen behaves strangely [quirk]

### ISSUE THREAD

**Issue by un-logic** [SecUSo/privacy-friendly-activity-tracker#9]
Steps to reproduce:
1. Open application and notice 'Pedometer' caption at the top;
2. Open 'About' screen via sidebar and notice 'Pedometer about' caption appear;
3. Open 'Pedometer' screen via sidebar, notice 'Pedometer about' caption still there instead of 'Pedometer' caption;
4. Repeat steps 2 to 3 couple more times;
5. Navigate with 'Back' key, notice each time you are closing an instance of one of those screens.
I suggest to use same code for 'About' screen as one for 'Help' screen.

**Comment by Yonjuni** [comment]
Solved in version 1.0.2
